#!/usr/bin/env python

import optparse,re,os,base64,urllib2,httplib,sys,urllib
httplib.HTTPConnection.debuglevel = 1

def checkRequiredArguments(opts, parser):
    missing_options = []
    for option in parser.option_list:
        if re.match(r'^\[REQUIRED\]', option.help) and eval('opts.' + option.dest) == None:
            missing_options.extend(option._long_opts)
    if len(missing_options) > 0:
        parser.error('Missing REQUIRED parameters: ' + str(missing_options))

def readFile(fn):
	f = open(fn,"r")
	x = f.read()
	f.close()
	return x

def installSslService(hostname,user,passwd,service,keys):
	authstring="%s:%s" % (user,passwd)
	auth="Basic " + base64.b64encode(authstring)
	crt_data=readFile(keys['crt'])
	ca_data=readFile(keys['ca'])
	key_data=readFile(keys['key'])
	# print crt_data
	keydata = urllib.urlencode({'crt': crt_data, 'ca': ca_data, 'key': key_data})
	url = "https://%s:2087/xml-api/install_service_ssl_certificate?api.version=1&service=%s&%s" % (hostname,service,keydata)
	request = urllib2.Request(url)
	request.add_header('Authorization', auth)
	opener = urllib2.build_opener()
	whmdata = opener.open(request).read()
	return whmdata


def main():
        p = optparse.OptionParser(description='Install Service SSL on a cPanel Server via Command Line.',
                                    prog='cpanel-install-service-ssl',
                                    version='cpanel-install-service-ssl 0.1',
                                    usage='%prog -h')

        p.add_option("--hostname", dest="hostname", type="string", help="[REQUIRED] The hostname of the host you intend on installing the SSL cert on.")
        p.add_option("--username", dest="username", type="string", help="WHM username, normally root. If not supplied will use root")
        p.add_option("--password", dest="password", type="string", help="[REQUIRED] Password of the user.")
        p.add_option("--service", dest="service", type="string", help="[REQUIRED] These services are ftp, exim, dovecot, courier, and cpanel.")
        p.add_option("--crt", dest="crt", type="string", help="[REQUIRED] Path to the KEY .crt file.")
        p.add_option("--key", dest="key", type="string", help="[REQUIRED] Path to the KEY .key file.")
        p.add_option("--ca", dest="ca", type="string", help="[REQUIRED] Path to the KEY .cabundle file.")

        options, arguments = p.parse_args()
        checkRequiredArguments(options, p)

        files = {}
        files['crt'] = options.crt
        files['key'] = options.key
        files['ca'] = options.ca
        for name , fn in files.items():
        	if not os.path.isfile(fn):
        		p.error(name + ' file is missing.')
        
        if not options.username:
        	options.username = "root"
        print installSslService(options.hostname,options.username,options.password,options.service,files)

if __name__ == '__main__':
        main()